# Generated by Django 3.1.6 on 2022-02-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='taking_passengers',
            new_name='pets',
        ),
    ]
